server:
  port: 8087

spring:
  application:
    name: API-GATEWAY
#  cloud:
#   gateway:
#     routes:
#       - id: super-admin-route
#         uri: lb://TARGETSERVICE
#         predicates:
#           - Path=/target/sadmin
#         filters:
#           - name: JwtRoleCheckFilter
#             args:
#              requiredRole: ROLE_USER,ROLE_ADMIN
#
#       - id: user-route
#         uri: lb://TARGETSERVICE
#         predicates:
#            - Path=/target/user
#         filters:
#           - name: JwtRoleCheckFilter
#             args:
#              requiredRole: ROLE_USER
#
#       - id: admin-route
#         uri: lb://TARGETSERVICE
#         predicates:
#            - Path=/target/admin
#         filters:
#           - name: JwtRoleCheckFilter
#             args:
#              requiredRole: ROLE_ADMIN
#
#       - id: all-route
#         uri: lb://TARGETSERVICE
#         predicates:
#            - Path=/target/all
#         filters:
#           - name: JwtRoleCheckFilter
#
#       - id: AUTHSERVICE
#         uri: lb://AUTHSERVICE
#         predicates:
#           - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/